package com.secitriy.analyzer.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CheckListAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckListAllPropertiesEquals(CheckList expected, CheckList actual) {
        assertCheckListAutoGeneratedPropertiesEquals(expected, actual);
        assertCheckListAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckListAllUpdatablePropertiesEquals(CheckList expected, CheckList actual) {
        assertCheckListUpdatableFieldsEquals(expected, actual);
        assertCheckListUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckListAutoGeneratedPropertiesEquals(CheckList expected, CheckList actual) {
        assertThat(expected)
            .as("Verify CheckList auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckListUpdatableFieldsEquals(CheckList expected, CheckList actual) {
        assertThat(expected)
            .as("Verify CheckList relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckListUpdatableRelationshipsEquals(CheckList expected, CheckList actual) {}
}
