package com.secitriy.analyzer.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CheckLisItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckLisItemAllPropertiesEquals(CheckLisItem expected, CheckLisItem actual) {
        assertCheckLisItemAutoGeneratedPropertiesEquals(expected, actual);
        assertCheckLisItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckLisItemAllUpdatablePropertiesEquals(CheckLisItem expected, CheckLisItem actual) {
        assertCheckLisItemUpdatableFieldsEquals(expected, actual);
        assertCheckLisItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckLisItemAutoGeneratedPropertiesEquals(CheckLisItem expected, CheckLisItem actual) {
        assertThat(expected)
            .as("Verify CheckLisItem auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckLisItemUpdatableFieldsEquals(CheckLisItem expected, CheckLisItem actual) {
        assertThat(expected)
            .as("Verify CheckLisItem relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getValue()).as("check value").isEqualTo(actual.getValue()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCheckLisItemUpdatableRelationshipsEquals(CheckLisItem expected, CheckLisItem actual) {
        assertThat(expected)
            .as("Verify CheckLisItem relationships")
            .satisfies(e -> assertThat(e.getCheckList()).as("check checkList").isEqualTo(actual.getCheckList()));
    }
}
