package com.secitriy.analyzer.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StateAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStateAllPropertiesEquals(State expected, State actual) {
        assertStateAutoGeneratedPropertiesEquals(expected, actual);
        assertStateAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStateAllUpdatablePropertiesEquals(State expected, State actual) {
        assertStateUpdatableFieldsEquals(expected, actual);
        assertStateUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStateAutoGeneratedPropertiesEquals(State expected, State actual) {
        assertThat(expected)
            .as("Verify State auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStateUpdatableFieldsEquals(State expected, State actual) {
        assertThat(expected)
            .as("Verify State relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStateUpdatableRelationshipsEquals(State expected, State actual) {
        assertThat(expected)
            .as("Verify State relationships")
            .satisfies(e -> assertThat(e.getCountry()).as("check country").isEqualTo(actual.getCountry()));
    }
}
