package com.secitriy.analyzer.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TestCheckLisItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTestCheckLisItemAllPropertiesEquals(TestCheckLisItem expected, TestCheckLisItem actual) {
        assertTestCheckLisItemAutoGeneratedPropertiesEquals(expected, actual);
        assertTestCheckLisItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTestCheckLisItemAllUpdatablePropertiesEquals(TestCheckLisItem expected, TestCheckLisItem actual) {
        assertTestCheckLisItemUpdatableFieldsEquals(expected, actual);
        assertTestCheckLisItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTestCheckLisItemAutoGeneratedPropertiesEquals(TestCheckLisItem expected, TestCheckLisItem actual) {
        assertThat(expected)
            .as("Verify TestCheckLisItem auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTestCheckLisItemUpdatableFieldsEquals(TestCheckLisItem expected, TestCheckLisItem actual) {
        assertThat(expected)
            .as("Verify TestCheckLisItem relevant properties")
            .satisfies(e -> assertThat(e.getMarked()).as("check marked").isEqualTo(actual.getMarked()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTestCheckLisItemUpdatableRelationshipsEquals(TestCheckLisItem expected, TestCheckLisItem actual) {
        assertThat(expected)
            .as("Verify TestCheckLisItem relationships")
            .satisfies(e -> assertThat(e.getChecklistitem()).as("check checklistitem").isEqualTo(actual.getChecklistitem()))
            .satisfies(e -> assertThat(e.getTestCheckList()).as("check testCheckList").isEqualTo(actual.getTestCheckList()));
    }
}
